In [2]:
import pandas as pd
import numpy as np
import nltk

In [3]:
data = pd.read_csv('/content/Preprocessed_DonorsChoose_dataset.csv')

In [4]:
data.head()
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7770 entries, 0 to 7769
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7770 non-null   object
 1   teacher_prefix                                7770 non-null   object
 2   school_state                                  7770 non-null   object
 3   project_grade_category                        7770 non-null   object
 4   project_subject_categories                    7770 non-null   object
 5   project_subject_subcategories                 7770 non-null   object
 6   teacher_number_of_previously_posted_projects  7770 non-null   int64
 7   project_is_approved                           7770 non-null   int64
 8   price                                         7770 non-null   float64
 9   quantity                                      7770 non-null   int64
 10  cleaned_titles                                7767 non-null   object
 11  cleaned_essays                                7770 non-null   object
 12  cleaned_summary                               7769 non-null   object
 13  isdigit_summary                               7769 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 850.0+ KB

id                                              0
teacher_prefix                                  0
school_state                                    0
project_grade_category                          0
project_subject_categories                      0
project_subject_subcategories                   0
teacher_number_of_previously_posted_projects    0
project_is_approved                             0
price                                           0
quantity                                        0
cleaned_titles                                  3
cleaned_essays                                  0
cleaned_summary                                 1
isdigit_summary                                 1
dtype: int64

In [6]:
data['project_is_approved'].value_counts()

project_is_approved
1    6620
0    1150
Name: count, dtype: int64

In [7]:
X = data.drop(columns=['project_is_approved'])
y = data['project_is_approved']

# Convert all columns to string and concatenate row-wise
data['combined_text'] = X.astype(str).agg(' '.join, axis=1)

data[['combined_text', 'project_is_approved']].head()

                                       combined_text  project_is_approved
0  p253737 mrs in grades_prek_2 literacy_language...                    0
1  p258326 mr fl grades_6_8 history_civics_health...                    1
2  p182444 ms az grades_6_8 health_sports health_...                    0
3  p246581 mrs ky grades_prek_2 literacy_language...                    1
4  p104768 mrs tx grades_prek_2 math_science math...                    1

In [8]:
import pandas as pd
import string
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [11]:
def preprocess(text_input):
    if pd.isna(text_input):
        return []

    # 1	 Strip whitespace
    text_input = text_input.strip()

    # 2	 Remove punctuation
    translator = str.maketrans('', '', string.punctuation)
    text_input = text_input.translate(translator)

    import re
    text_input = re.sub(r'[^a-zA-Z0-9 ]','',text_input)

    # 3	 Convert to lowercase
    text_input = text_input.lower()

    # 4	 Tokenize
    tokens = nltk.word_tokenize(text_input)


    # 5	 Remove stopwords
    stop_words = set(stopwords.words('english'))
    stop_word_removed = [word for word in tokens if word not in stop_words]

    # 6	 Lemmatization
    lemmatizer = WordNetLemmatizer()
    lemmitized_text = [lemmatizer.lemmatize(word) for word in stop_word_removed]

    return lemmitized_text


data['preprocess_text'] = data['combined_text'].apply(preprocess)

data.head()

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary,combined_text,preprocess_text
0,p253737,mrs,in,grades_prek_2,literacy_language,esl_literacy,0,0,154.60,23,educational support english learners home,students english learners working english seco...,students_need_opportunities_practice_beginning...,0.0,p253737 mrs in grades_prek_2 literacy_language...,"[p253737, mr, gradesprek2, literacylanguage, e..."
1,p258326,mr,fl,grades_6_8,history_civics_health_sports,civics_government_teamsports,7,1,299.00,1,wanted projector hungry learners,students arrive school eager learn polite gene...,students_need_projector_help_viewing_education...,0.0,p258326 mr fl grades_6_8 history_civics_health...,"[p258326, mr, fl, grades68, historycivicshealt..."
2,p182444,ms,az,grades_6_8,health_sports,health_wellness_teamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,students_need_shine_guards_athletic_socks_socc...,0.0,p182444 ms az grades_6_8 health_sports health_...,"[p182444, m, az, grades68, healthsports, healt..."
3,p246581,mrs,ky,grades_prek_2,literacy_language_math_science,literacy_mathematics,4,1,232.90,4,techie kindergarteners,work unique school filled esl english second l...,students_need_engage_reading_math_way_inspire_...,0.0,p246581 mrs ky grades_prek_2 literacy_language...,"[p246581, mr, ky, gradesprek2, literacylanguag..."
4,p104768,mrs,tx,grades_prek_2,math_science,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,students_need_hands_practice_mathematics_fun_p...,0.0,p104768 mrs tx grades_prek_2 math_science math...,"[p104768, mr, tx, gradesprek2, mathscience, ma..."

In [12]:
data['clean_msg'] = data['preprocess_text'].apply(lambda x: ' '.join(x))
data.head()

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary,combined_text,preprocess_text,clean_msg
0,p253737,mrs,in,grades_prek_2,literacy_language,esl_literacy,0,0,154.60,23,educational support english learners home,students english learners working english seco...,students_need_opportunities_practice_beginning...,0.0,p253737 mrs in grades_prek_2 literacy_language...,"[p253737, mr, gradesprek2, literacylanguage, e...",p253737 mr gradesprek2 literacylanguage esllit...
1,p258326,mr,fl,grades_6_8,history_civics_health_sports,civics_government_teamsports,7,1,299.00,1,wanted projector hungry learners,students arrive school eager learn polite gene...,students_need_projector_help_viewing_education...,0.0,p258326 mr fl grades_6_8 history_civics_health...,"[p258326, mr, fl, grades68, historycivicshealt...",p258326 mr fl grades68 historycivicshealthspor...
2,p182444,ms,az,grades_6_8,health_sports,health_wellness_teamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,students_need_shine_guards_athletic_socks_socc...,0.0,p182444 ms az grades_6_8 health_sports health_...,"[p182444, m, az, grades68, healthsports, healt...",p182444 m az grades68 healthsports healthwelln...
3,p246581,mrs,ky,grades_prek_2,literacy_language_math_science,literacy_mathematics,4,1,232.90,4,techie kindergarteners,work unique school filled esl english second l...,students_need_engage_reading_math_way_inspire_...,0.0,p246581 mrs ky grades_prek_2 literacy_language...,"[p246581, mr, ky, gradesprek2, literacylanguag...",p246581 mr ky gradesprek2 literacylanguagemath...
4,p104768,mrs,tx,grades_prek_2,math_science,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,students_need_hands_practice_mathematics_fun_p...,0.0,p104768 mrs tx grades_prek_2 math_science math...,"[p104768, mr, tx, gradesprek2, mathscience, ma...",p104768 mr tx gradesprek2 mathscience mathemat...

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,2))
X_tfidf = tfidf_vectorizer.fit_transform(data['clean_msg'])
y = data['project_is_approved']

In [14]:
from sklearn.model_selection import train_test_split
X_tfidf_train, X_tfidf_test, y_tfidf_train, y_tfidf_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

# TF IDF - MultinomialNB

In [15]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nb_model = MultinomialNB()
nb_model.fit(X_tfidf_train, y_tfidf_train)
y_pred = nb_model.predict(X_tfidf_test)

print(accuracy_score(y_tfidf_test,y_pred))
print(classification_report(y_tfidf_test,y_pred))
print(confusion_matrix(y_tfidf_test,y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# TF-IDF - Logistic REGRESSION

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

lr = LogisticRegression(max_iter=1000)
lr.fit(X_tfidf_train, y_tfidf_train)

y_pred = lr.predict(X_tfidf_test)

print(accuracy_score(y_tfidf_test,y_pred))
print(classification_report(y_tfidf_test, y_pred))
print(confusion_matrix(y_tfidf_test, y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# TF IDF - Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs= -1)
rf_model.fit(X_tfidf_train, y_tfidf_train)
y_pred = rf_model.predict(X_tfidf_test)

print(accuracy_score(y_tfidf_test,y_pred))
print(classification_report(y_tfidf_test,y_pred))
print(confusion_matrix(y_tfidf_test,y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# SVM

In [19]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(class_weight="balanced")

svm_model.fit(X_tfidf_train, y_tfidf_train)
y_pred = svm_model.predict(X_tfidf_test)

print(accuracy_score(y_tfidf_test,y_pred))
print(classification_report(y_tfidf_test,y_pred))
print(confusion_matrix(y_tfidf_test,y_pred))

0.8449163449163449
              precision    recall  f1-score   support

           0       0.37      0.06      0.10       232
           1       0.86      0.98      0.92      1322

    accuracy                           0.84      1554
   macro avg       0.61      0.52      0.51      1554
weighted avg       0.78      0.84      0.79      1554

[[  13  219]
 [  22 1300]]

# Word2Vec

In [23]:
!pip install gensim
from gensim.models import Word2Vec

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 78.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [24]:
import numpy as np

# First, correctly define corpus from the preprocessed text data
corpus = data['preprocess_text'].tolist()

# Then, train the Word2Vec model using this correct corpus
w2v_model = Word2Vec(sentences=corpus,
                     vector_size=50,
                     min_count = 1,
                     workers = 4, window = 3, sg=1)

def sentence_embedding(words):
  vectors = [w2v_model.wv[w] for w in words if w in w2v_model.wv]
  if len(vectors) == 0:
    return np.zeros(w2v_model.vector_size)
  else:
    return np.mean(vectors, axis=0)

# Finally, create embeddings
x_embeddings = np.array([sentence_embedding(msg) for msg in corpus])
print(x_embeddings.shape)

(7770, 50)

In [25]:
from sklearn.model_selection import train_test_split

X_w2v = x_embeddings
y = data['project_is_approved']
X_w2v_train, X_w2v_test, y_w2v_train, y_w2v_test = train_test_split(X_w2v, y, test_size=0.2, random_state=42)

# Logistic Regression

In [26]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_w2v_train, y_w2v_train)

y_pred = lr.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test, y_pred))
print(confusion_matrix(y_w2v_test, y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_w2v_train, y_w2v_train)
y_pred = rf_model.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test,y_pred))
print(confusion_matrix(y_w2v_test,y_pred))

0.8513513513513513
              precision    recall  f1-score   support

           0       1.00      0.00      0.01       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.93      0.50      0.46      1554
weighted avg       0.87      0.85      0.78      1554

[[   1  231]
 [   0 1322]]

#SVM

In [28]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(class_weight="balanced")

svm_model.fit(X_w2v_train, y_w2v_train)
y_pred = svm_model.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test,y_pred))
print(confusion_matrix(y_w2v_test,y_pred))

0.6254826254826255
              precision    recall  f1-score   support

           0       0.23      0.64      0.34       232
           1       0.91      0.62      0.74      1322

    accuracy                           0.63      1554
   macro avg       0.57      0.63      0.54      1554
weighted avg       0.81      0.63      0.68      1554

[[148  84]
 [498 824]]

In [29]:
from tensorflow.keras.layers import Input, Dense, Dropout, concatenate, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

# Convert sparse TF-IDF matrix to dense
X_tfidf_train_dense = X_tfidf_train.toarray()

# TF-IDF Branch

input_tfidf = Input(shape=(X_tfidf_train_dense.shape[1],))

x1 = Dense(512, activation='relu',
           kernel_initializer='he_uniform',
           kernel_regularizer=regularizers.l2(0.001))(input_tfidf)
x1 = BatchNormalization()(x1)
x1 = Dropout(0.5)(x1)

x1 = Dense(256, activation='relu',
           kernel_initializer='he_uniform')(x1)
x1 = Dropout(0.4)(x1)

# Word2Vec Branch

input_w2v = Input(shape=(X_w2v_train.shape[1],))

x2 = Dense(256, activation='relu',
           kernel_initializer='glorot_uniform')(input_w2v)
x2 = BatchNormalization()(x2)
x2 = Dropout(0.4)(x2)

x2 = Dense(128, activation='relu')(x2)


# Merge Branches

merged = concatenate([x1, x2])

x = Dense(256, activation='relu',
          kernel_initializer='he_uniform')(merged)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

x = Dense(128, activation='relu')(x)
x = Dropout(0.4)(x)

# Output layer (Binary Classification)
output = Dense(1, activation='sigmoid')(x)

# Build Model
model = Model(inputs=[input_tfidf, input_w2v], outputs=output)

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 483053)    │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │ 247,323,6… │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_1       │ (None, 50)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 512)       │      2,048 │ dense[0][0]       │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 256)       │     13,056 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 512)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256)       │      1,024 │ dense_2[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 256)       │    131,328 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 256)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 256)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     32,896 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 384)       │          0 │ dropout_1[0][0],  │
│ (Concatenate)       │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 256)       │     98,560 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256)       │      1,024 │ dense_4[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 256)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 128)       │     32,896 │ dropout_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_4 (Dropout) │ (None, 128)       │          0 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 1)         │        129 │ dropout_4[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 247,636,609 (944.66 MB)

 Trainable params: 247,634,561 (944.65 MB)

 Non-trainable params: 2,048 (8.00 KB)